## This Notebook contains fundamentals for `Tensor` and `Pytorch` with `CPU` and `GPU` usage at the bottom

**Note** : I have installed and setup `cuda` on my local hardware. You can run this on google colab if you donot have GPU availability support with python on your local machine. Else, error might be thrown.

In [115]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


Pytorch tensors are created using `torch.Tensor()`

`scalar` - (1)

`vector` - [1, 2, 3]

`MATRIX` = [[1, 2, 3],[4, 5, 6]]

`TENSOR` = [ [[1, 2, 3], [4, 5, 6]],
           [[1, 2, 3], [4, 5, 6]] ]

Naming convention for `scalar and vector` are `lowecase` whereas for `MATRIX and TENSORS`, its `UPPERCASE`.


Neural Network start with random `TENSORS` passed at the beginning which is `adjusted and updated` by the Neural Network each time looking at the data.

In [116]:
 # Creating random tensors using rand()

 random_image = torch.rand(244, 244, 3) #height, width, color_channel
 random_image.shape, random_image.ndim

(torch.Size([244, 244, 3]), 3)

In [117]:
# Creating a range of tensors

ten_tensors = torch.arange(1, 11, 1)
ten_tensors


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
# Copying shape of other tensors and making same shape with '0'

ten_zeroes = torch.zeros_like(ten_tensors)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor data-types
**Note :** Tensor datatype is one of the three common issue that will cause error in PyTorch & Deep Learning.

Those 3 are:
1. Tensors not right datatype (float32/float16)
2. Tensors not right shape
3. Tensors not on the right device (GPU/CPU)

In [119]:
# Float32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # dtype of tensor i.e (float32 or float16)
                               device = None, # which device is tensor on
                               requires_grad = False) # whether or not to track tensor gradients with this tensor operations

float_32_tensor

tensor([3., 6., 9.])

In [120]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [121]:
(float_16_tensor * float_32_tensor)

tensor([ 9., 36., 81.])

### Solving tensor issue (Basics)

1. Tensor not right datatype - to do get datatype from a tensor, can use `tensor.dtype`

2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`

3. Tensor not on the right device - to get device from a tensor, can use `tensor.device`


In [122]:
some_tensor = torch.rand(5, 5)
some_tensor

tensor([[0.8006, 0.0750, 0.6011, 0.1838, 0.3278],
        [0.1842, 0.3922, 0.2608, 0.6431, 0.8455],
        [0.3549, 0.7987, 0.0195, 0.3426, 0.1999],
        [0.0783, 0.4362, 0.5973, 0.8781, 0.7217],
        [0.7007, 0.0852, 0.5051, 0.3764, 0.9566]])

In [123]:
# Getting details of tensor

print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.8006, 0.0750, 0.6011, 0.1838, 0.3278],
        [0.1842, 0.3922, 0.2608, 0.6431, 0.8455],
        [0.3549, 0.7987, 0.0195, 0.3426, 0.1999],
        [0.0783, 0.4362, 0.5973, 0.8781, 0.7217],
        [0.7007, 0.0852, 0.5051, 0.3764, 0.9566]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([5, 5])
Device tensor is on : cpu


### Manipulating tensors

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [124]:
random_tensors = torch.tensor([1, 2, 3])
random_tensors + 10

tensor([11, 12, 13])

In [125]:
random_tensors * 10

tensor([10, 20, 30])

In [126]:
random_tensors - 10

tensor([-9, -8, -7])

In [127]:
# Pytorch inbuilt functions

torch.mul(random_tensors, 10)

tensor([10, 20, 30])

In [128]:
torch.add(random_tensors, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element wise multiplication
2. Matrix multiplication (dot product)

In [129]:
# Element wise multiplication

tensor = torch.tensor([[1, 2, 3],[4, 5, 6]])
print(tensor * tensor)

tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [130]:
%%time

# Matrix multiplication
torch.matmul(tensor, tensor.T) # torch.mm() is same as torch.matmul()

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[14, 32],
        [32, 77]])

In [131]:
%%time

# @ can be used for matrix multiplication
tensor @ tensor.T

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[14, 32],
        [32, 77]])

In [132]:
tensor.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

### Datatype mismatch error encountered

In [133]:
# Default datatype of a tensor is int64 which causes below error
torch.mean(tensor)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [134]:
# So, fulfiling the requirement of mean()
torch.mean(tensor.type(torch.float32))

tensor(3.5000)

### Reshaping, Stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as original tensor

* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

* Squeeze - removes all `1` dimensions from a tensor

* Unsqueeze - add a `1` dimension to a target tensor

* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way





In [135]:
import torch

x = torch.arange( 1., 21.)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20.])

In [136]:
# Adding extra dimension

x_reshaped = x.reshape(4, 5)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.]])

In [137]:
# Change the view

x_view = x.view(20, 1)
x_view

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [13.],
        [14.],
        [15.],
        [16.],
        [17.],
        [18.],
        [19.],
        [20.]])

changing `x.view()` changes x because (view of a tensor shares the same memory as the original input)

In [138]:
x_view[:, 0:][0] = 123
x_view

tensor([[123.],
        [  2.],
        [  3.],
        [  4.],
        [  5.],
        [  6.],
        [  7.],
        [  8.],
        [  9.],
        [ 10.],
        [ 11.],
        [ 12.],
        [ 13.],
        [ 14.],
        [ 15.],
        [ 16.],
        [ 17.],
        [ 18.],
        [ 19.],
        [ 20.]])

In [139]:
# Stacking tensors on top of each other

x_stacked = torch.stack([x, x], dim = 0)
x_stacked

tensor([[123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
          13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
        [123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
          13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.]])

In [140]:
# Squeeze removes 1 dimension from tensor
# Unsqueeze does opposite

x_squeezed = x_view.squeeze()
x_squeezed

tensor([123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
         13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.])

In [141]:
x_unsqueezed = torch.unsqueeze(x_squeezed, dim = 1)
x_unsqueezed

tensor([[123.],
        [  2.],
        [  3.],
        [  4.],
        [  5.],
        [  6.],
        [  7.],
        [  8.],
        [  9.],
        [ 10.],
        [ 11.],
        [ 12.],
        [ 13.],
        [ 14.],
        [ 15.],
        [ 16.],
        [ 17.],
        [ 18.],
        [ 19.],
        [ 20.]])

In [142]:
# Permute - rearranges the dimensions of a target dimension in a specified order

x_original = torch.rand(size = (224, 224, 3))
x_original.size()


torch.Size([224, 224, 3])

In [143]:
# Lets switch the dimension of above image tensors(color channel at first)

x_permuted = x_original.permute(2, 0, 1)
x_permuted.size()

torch.Size([3, 224, 224])

In [144]:
x_permuted

tensor([[[3.7828e-01, 3.4360e-01, 9.7381e-02,  ..., 5.8872e-01,
          8.5363e-01, 8.5264e-02],
         [1.7739e-01, 2.6131e-01, 1.9997e-01,  ..., 9.9854e-02,
          5.7894e-01, 8.3744e-01],
         [3.7173e-01, 4.8278e-01, 7.6549e-01,  ..., 1.6582e-01,
          8.9461e-01, 3.7256e-01],
         ...,
         [2.0061e-01, 7.9517e-01, 1.3275e-01,  ..., 1.2605e-01,
          3.2957e-01, 7.1832e-01],
         [6.3677e-01, 2.1118e-04, 8.6567e-01,  ..., 4.2293e-01,
          3.4234e-01, 8.0179e-01],
         [1.7212e-01, 8.7170e-01, 9.9916e-01,  ..., 3.3417e-02,
          3.4141e-01, 4.1164e-01]],

        [[7.5868e-01, 9.0743e-01, 8.0542e-01,  ..., 3.7141e-01,
          8.8768e-01, 6.7670e-01],
         [8.4311e-01, 8.2269e-01, 1.9314e-01,  ..., 5.4581e-01,
          1.7295e-01, 1.7357e-01],
         [8.4506e-01, 3.9117e-02, 3.0340e-01,  ..., 6.1376e-01,
          2.8429e-01, 8.9664e-02],
         ...,
         [6.6957e-01, 3.1242e-01, 5.2565e-01,  ..., 5.1099e-01,
          7.370

In [145]:
x_permuted[0, 0, 0] = 1
x_original

tensor([[[1.0000e+00, 7.5868e-01, 1.1114e-01],
         [3.4360e-01, 9.0743e-01, 1.5564e-01],
         [9.7381e-02, 8.0542e-01, 4.9125e-01],
         ...,
         [5.8872e-01, 3.7141e-01, 5.5843e-01],
         [8.5363e-01, 8.8768e-01, 4.7859e-01],
         [8.5264e-02, 6.7670e-01, 9.2201e-01]],

        [[1.7739e-01, 8.4311e-01, 2.4707e-01],
         [2.6131e-01, 8.2269e-01, 5.4558e-01],
         [1.9997e-01, 1.9314e-01, 6.0002e-01],
         ...,
         [9.9854e-02, 5.4581e-01, 6.9702e-01],
         [5.7894e-01, 1.7295e-01, 4.0425e-01],
         [8.3744e-01, 1.7357e-01, 8.1314e-01]],

        [[3.7173e-01, 8.4506e-01, 5.9468e-01],
         [4.8278e-01, 3.9117e-02, 9.4892e-01],
         [7.6549e-01, 3.0340e-01, 2.4206e-01],
         ...,
         [1.6582e-01, 6.1376e-01, 4.1365e-01],
         [8.9461e-01, 2.8429e-01, 1.6293e-01],
         [3.7256e-01, 8.9664e-02, 9.8926e-01]],

        ...,

        [[2.0061e-01, 6.6957e-01, 1.6838e-02],
         [7.9517e-01, 3.1242e-01, 9.2861e-01]

In [146]:
# Indexing / Slicing

mat = torch.rand(2, 2, 3, 2)
mat

tensor([[[[0.4339, 0.9958],
          [0.0043, 0.5647],
          [0.5969, 0.9205]],

         [[0.7638, 0.3454],
          [0.7837, 0.2460],
          [0.6713, 0.7268]]],


        [[[0.9297, 0.2856],
          [0.9050, 0.6583],
          [0.6611, 0.3769]],

         [[0.4459, 0.8423],
          [0.2854, 0.2232],
          [0.7262, 0.7220]]]])

In [147]:
mat[0, :, :]

tensor([[[0.4339, 0.9958],
         [0.0043, 0.5647],
         [0.5969, 0.9205]],

        [[0.7638, 0.3454],
         [0.7837, 0.2460],
         [0.6713, 0.7268]]])

### Reproducibility (trying to take random out of random)

`neural network`start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again

use `randomseed`

### Putting tensors (and models) on the GPU


In [148]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [149]:
tensor_on_cpu = torch.tensor([1, 2, 3], device = "cpu") # cpu is default
device1 = tensor.device
tensor, device1

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 device(type='cpu'))

In [150]:
# moving tensor to GPU (if available)
tensor_on_gpu = tensor_on_cpu.to(device)
tensor_on_gpu, tensor_to_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [155]:
!nvidia-smi

Fri Aug 25 13:48:44 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.13                 Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060 ...  WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P8               8W /  30W |    108MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### Numpy doesnot work on GPU

In [152]:
# tensor_on_gpu is currently working on GPU, which is not supported by Numpy

tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [154]:
# Moving tensor back to cpu
tensor_on_gpu.to('cpu').numpy()


array([1, 2, 3], dtype=int64)