## This Notebook contains fundamentals for `Tensor` and `Pytorch` with `CPU` and `GPU` usage at the bottom

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


Pytorch tensors are created using `torch.Tensor()`

`scalar` - (1)

`vector` - [1, 2, 3]

`MATRIX` = [[1, 2, 3],[4, 5, 6]]

`TENSOR` = [ [[1, 2, 3], [4, 5, 6]],
           [[1, 2, 3], [4, 5, 6]] ]

Naming convention for `scalar and vector` are `lowecase` whereas for `MATRIX and TENSORS`, its `UPPERCASE`.


Neural Network start with random `TENSORS` passed at the beginning which is `adjusted and updated` by the Neural Network each time looking at the data.

In [2]:
 # Creating random tensors using rand()

 random_image = torch.rand(244, 244, 3) #height, width, color_channel
 random_image.shape, random_image.ndim

(torch.Size([244, 244, 3]), 3)

In [3]:
# Creating a range of tensors

ten_tensors = torch.arange(1, 11, 1)
ten_tensors


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Copying shape of other tensors and making same shape with '0'

ten_zeroes = torch.zeros_like(ten_tensors)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor data-types
**Note :** Tensor datatype is one of the three common issue that will cause error in PyTorch & Deep Learning.

Those 3 are:
1. Tensors not right datatype (float32/float16)
2. Tensors not right shape
3. Tensors not on the right device (GPU/CPU)

In [5]:
# Float32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # dtype of tensor i.e (float32 or float16)
                               device = None, # which device is tensor on
                               requires_grad = False) # whether or not to track tensor gradients with this tensor operations

float_32_tensor

tensor([3., 6., 9.])

In [6]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [7]:
(float_16_tensor * float_32_tensor)

tensor([ 9., 36., 81.])

### Solving tensor issue (Basics)

1. Tensor not right datatype - to do get datatype from a tensor, can use `tensor.dtype`

2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`

3. Tensor not on the right device - to get device from a tensor, can use `tensor.device`


In [8]:
some_tensor = torch.rand(5, 5)
some_tensor

tensor([[0.4115, 0.0761, 0.3307, 0.4234, 0.5012],
        [0.3573, 0.2641, 0.8802, 0.2001, 0.8899],
        [0.9665, 0.5191, 0.9036, 0.8884, 0.3983],
        [0.2842, 0.1403, 0.9605, 0.7942, 0.3033],
        [0.8613, 0.9432, 0.6249, 0.7590, 0.9455]])

In [9]:
# Getting details of tensor

print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.4115, 0.0761, 0.3307, 0.4234, 0.5012],
        [0.3573, 0.2641, 0.8802, 0.2001, 0.8899],
        [0.9665, 0.5191, 0.9036, 0.8884, 0.3983],
        [0.2842, 0.1403, 0.9605, 0.7942, 0.3033],
        [0.8613, 0.9432, 0.6249, 0.7590, 0.9455]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([5, 5])
Device tensor is on : cpu


### Manipulating tensors

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [10]:
random_tensors = torch.tensor([1, 2, 3])
random_tensors + 10

tensor([11, 12, 13])

In [11]:
random_tensors * 10

tensor([10, 20, 30])

In [12]:
random_tensors - 10

tensor([-9, -8, -7])

In [13]:
# Pytorch inbuilt functions

torch.mul(random_tensors, 10)

tensor([10, 20, 30])

In [14]:
torch.add(random_tensors, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element wise multiplication
2. Matrix multiplication (dot product)

In [15]:
# Element wise multiplication

tensor = torch.tensor([[1, 2, 3],[4, 5, 6]])
print(tensor * tensor)

tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [16]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor.T) # torch.mm() is same as torch.matmul()

UsageError: Line magic function `%%time` not found.


In [17]:
# @ can be used for matrix multiplication
%%time
tensor @ tensor.T

UsageError: Line magic function `%%time` not found.


In [18]:
tensor.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

### Datatype mismatch error encountered

In [19]:
torch.mean(tensor)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(tensor.type(torch.float32))

### Reshaping, Stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as original tensor

* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

* Squeeze - removes all `1` dimensions from a tensor

* Unsqueeze - add a `1` dimension to a target tensor

* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way





In [ ]:
import torch

x = torch.arange( 1., 21.)
x

In [ ]:
# Adding extra dimension

x_reshaped = x.reshape(4, 5)
x_reshaped

In [20]:
# Change the view

x_view = x.view(20, 1)
x_view

NameError: name 'x' is not defined

changing `x.view()` changes x because (view of a tensor shares the same memory as the original input)

In [21]:
x_view[:, 0:][0] = 123
x_view

NameError: name 'x_view' is not defined

In [22]:
# Stacking tensors on top of each other

x_stacked = torch.stack([x, x], dim = 0)
x_stacked

NameError: name 'x' is not defined

In [23]:
# Squeeze removes 1 dimension from tensor
# Unsqueeze does opposite

x_squeezed = x_view.squeeze()
x_squeezed

NameError: name 'x_view' is not defined

In [24]:
x_unsqueezed = torch.unsqueeze(x_squeezed, dim = 1)
x_unsqueezed

NameError: name 'x_squeezed' is not defined

In [25]:
# Permute - rearranges the dimensions of a target dimension in a specified order

x_original = torch.rand(size = (224, 224, 3))
x_original.size()


torch.Size([224, 224, 3])

In [26]:
# Lets switch the dimension of above image tensors(color channel at first)

x_permuted = x_original.permute(2, 0, 1)
x_permuted.size()

torch.Size([3, 224, 224])

In [27]:
x_permuted

tensor([[[0.5026, 0.7786, 0.7666,  ..., 0.8700, 0.7194, 0.4978],
         [0.2347, 0.9349, 0.8869,  ..., 0.9523, 0.0197, 0.9701],
         [0.6737, 0.4413, 0.2013,  ..., 0.4978, 0.7296, 0.7330],
         ...,
         [0.8120, 0.0955, 0.1799,  ..., 0.0674, 0.4318, 0.9547],
         [0.8261, 0.5608, 0.2504,  ..., 0.2146, 0.1920, 0.5991],
         [0.2871, 0.2163, 0.7350,  ..., 0.0646, 0.8716, 0.2264]],

        [[0.7747, 0.6490, 0.2056,  ..., 0.0141, 0.6215, 0.5394],
         [0.4480, 0.2772, 0.3224,  ..., 0.9078, 0.6271, 0.6745],
         [0.5389, 0.9071, 0.1857,  ..., 0.3824, 0.7075, 0.5544],
         ...,
         [0.0031, 0.8531, 0.0079,  ..., 0.4148, 0.2971, 0.2421],
         [0.6321, 0.1236, 0.4196,  ..., 0.0983, 0.3878, 0.8915],
         [0.3759, 0.6114, 0.1857,  ..., 0.1755, 0.2561, 0.1133]],

        [[0.7543, 0.9996, 0.8877,  ..., 0.2733, 0.1999, 0.3146],
         [0.7466, 0.9264, 0.9835,  ..., 0.5032, 0.1138, 0.5132],
         [0.9858, 0.3918, 0.4193,  ..., 0.6236, 0.3447, 0.

In [28]:
x_permuted[0, 0, 0] = 1
x_original

tensor([[[1.0000, 0.7747, 0.7543],
         [0.7786, 0.6490, 0.9996],
         [0.7666, 0.2056, 0.8877],
         ...,
         [0.8700, 0.0141, 0.2733],
         [0.7194, 0.6215, 0.1999],
         [0.4978, 0.5394, 0.3146]],

        [[0.2347, 0.4480, 0.7466],
         [0.9349, 0.2772, 0.9264],
         [0.8869, 0.3224, 0.9835],
         ...,
         [0.9523, 0.9078, 0.5032],
         [0.0197, 0.6271, 0.1138],
         [0.9701, 0.6745, 0.5132]],

        [[0.6737, 0.5389, 0.9858],
         [0.4413, 0.9071, 0.3918],
         [0.2013, 0.1857, 0.4193],
         ...,
         [0.4978, 0.3824, 0.6236],
         [0.7296, 0.7075, 0.3447],
         [0.7330, 0.5544, 0.4917]],

        ...,

        [[0.8120, 0.0031, 0.2820],
         [0.0955, 0.8531, 0.3845],
         [0.1799, 0.0079, 0.6989],
         ...,
         [0.0674, 0.4148, 0.8228],
         [0.4318, 0.2971, 0.6846],
         [0.9547, 0.2421, 0.4150]],

        [[0.8261, 0.6321, 0.1944],
         [0.5608, 0.1236, 0.5620],
         [0.

In [29]:
# Indexing / Slicing

mat = torch.rand(2, 2, 3, 2)
mat

tensor([[[[0.7549, 0.8628],
          [0.6440, 0.7589],
          [0.8100, 0.2042]],

         [[0.5792, 0.2178],
          [0.6632, 0.1413],
          [0.7230, 0.5499]]],


        [[[0.1536, 0.3956],
          [0.4100, 0.5160],
          [0.4417, 0.0305]],

         [[0.2399, 0.0131],
          [0.9648, 0.2430],
          [0.3655, 0.2216]]]])

In [30]:
mat[0, :, :]

tensor([[[0.7549, 0.8628],
         [0.6440, 0.7589],
         [0.8100, 0.2042]],

        [[0.5792, 0.2178],
         [0.6632, 0.1413],
         [0.7230, 0.5499]]])

### Reproducibility (trying to take random out of random)

`neural network`start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again

use `randomseed`

### Putting tensors (and models) on the GPU


In [75]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [81]:
tensor_on_cpu = torch.tensor([1, 2, 3], device = "cpu") # cpu is default
device1 = tensor.device
tensor, device1

(tensor([1, 2, 3]), device(type='cpu'))

In [82]:
# moving tensor to GPU (if available)
tensor_on_gpu = tensor_on_cpu.to(device)
tensor_on_gpu, tensor_to_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [83]:
# !nvidia-smi

### Numpy doesnot work on GPU

In [91]:
tensor_on_gpu.numpy()


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [92]:
# Moving tensor back to cpu
tensor_on_gpu.to('cpu').numpy()


array([1, 2, 3], dtype=int64)